


--PART-A:-
--1 
SELECT *FROM DEPOSIT

--2
SELECT *FROM BORROW

--3
SELECT *FROM CUSTOMERS

--4
SELECT ACTNO,CNAME,AMOUNT FROM DEPOSIT

--5
SELECT LOANNO,AMOUNT FROM BORROW

--6
SELECT *FROM BORROW WHERE BNAME='ANDHERI'

--7
SELECT ACTNO,AMOUNT  FROM DEPOSIT WHERE ACTNO=106

--8 
SELECT CNAME FROM BORROW WHERE AMOUNT>5000

--9
SELECT CNAME FROM DEPOSIT WHERE ADATE>'1-12-96'

--10
SELECT CNAME FROM DEPOSIT WHERE ACTNO<105

--11
SELECT CNAME FROM CUSTOMERS WHERE CITY IN('NAGPUR','DELHI')

--12
SELECT CNAME,BNAME FROM DEPOSIT WHERE AMOUNT>'4000' AND ACOUNTNO<105

-- 13
SELECT CNAME FROM BORROW WHERE AMOUNT>='3000' AND AMOUNT<='8000'

--14
SELECT CNAME FROM DEPOSIT WHERE BNAME!='ANDHERI'

--15
SELECT ACOUNTNO,CNAME,AMOUNT FROM DEPOSIT WHERE BNAME in('AJNI','KAROL','M.G.ROAD')


--PART B
--1
SELECT TOP 5 * FROM DEPOSIT

--2
SELECT TOP 3 * FROM DEPOSIT WHERE AMOUNT > 1000

--3
SELECT TOP 5 LOANO,CNAME FROM BORROW WHERE BNAME <>'ANDHERI'

--4
SELECT DISTINCT CITY FROM CUSTOMERS

--5
SELECT DISTINCT BNAME FROM BRANCH

--PART C
--1
SELECT TOP 50 PERCENT *FROM BORROW

--2
SELECT TOP 10 PERCENT AMOUNT FROM DEPOSIT

--3
SELECT TOP 25 PERCENT *FROM DEPOSIT WHERE AMOUNT >5000

--4
SELECT TOP 10 PERCENT AMOUNT FROM BORROW

--5
SELECT DISTINCT CNAME,CITY FROM CUSTOMERS

--6
SELECT  *, AMOUNT+(AMOUNT*0.1) AS 'EXTRA_AMOUNT' FROM BORROW

--7
SELECT  *FROM BORROW WHERE (LOANO%2=0)